httplug:
    plugins:
        logger: ~
    discovery:
        client: 'auto'

    clients:
        http_client:
            factory: 'httplug.factory.guzzle6'
            http_methods_client: true
            plugins:
                - 'httplug.plugin.logger'
            config:
                timeout: 5
    classes:
        client: Http\Adapter\Guzzle6\Client
        message_factory: Http\Message\MessageFactory\GuzzleMessageFactory
        uri_factory: Http\Message\UriFactory\GuzzleUriFactory
        stream_factory: Http\Message\StreamFactory\GuzzleStreamFactory